import "@/src/styles/globals.css";
import { Inter } from "next/font/google";

import setTheme from "@/src/libs/set_theme";
import SessionProvider from "@/src/providers/SessionProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // need to abstract away logic to fetch the active sphere color theme eg: "Platform"
  // need to abstract away logic to fetch the active zone color theme eg: "Season Octagon Color"
  // need to abstract away logic to fetch the active gardener color theme eg: "Flower Octagon Color"

  return (
    <html lang="en">
      <body
        style={{
          ...(await setTheme("New test template", "sphere")),
          ...(await setTheme("New test template", "platform")),
        }}
        className={inter.className + " overflow-x-hidden"}
      >
        <Toaster
          toastOptions={{
            duration: 1000,
          }}
        />
        <>
          <main
            style={{
              ...(await setTheme("Platform", "user")),
            }}
            className="h-full w-full"
          >
            <SessionProvider>{children}</SessionProvider>
          </main>
          {/* <Footer /> */}
        </>
      </body>
    </html>
  );
}
